const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const dotenv = require('dotenv');
const User = require('../models/User');
const Product = require('../models/Product');

dotenv.config();

const seedData = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/farm-marketplace');
    console.log('Connected to MongoDB');

    // Clear existing data
    await User.deleteMany({});
    await Product.deleteMany({});
    console.log('Cleared existing data');

    // Create demo users
    const demoUsers = [
      {
        name: 'Demo Farmer',
        email: 'farmer@demo.com',
        password: 'demo123',
        role: 'farmer',
        phone: '555-0101',
        address: {
          street: '123 Farm Road',
          city: 'Farmville',
          state: 'CA',
          zipCode: '90210',
          country: 'USA'
        },
        farmerProfile: {
          farmName: 'Green Valley Farm',
          farmSize: 50,
          farmingMethods: ['Organic', 'Sustainable'],
          certifications: ['India Organic'],
          description: 'Family-owned organic farm specializing in fresh vegetables and fruits.',
          location: {
            latitude: 34.0522,
            longitude: -118.2437
          }
        },
        isVerified: true
      },
      {
        name: 'Demo Consumer',
        email: 'consumer@demo.com',
        password: 'demo123',
        role: 'consumer',
        phone: '555-0102',
        address: {
          street: '456 Main Street',
          city: 'Los Angeles',
          state: 'CA',
          zipCode: '90001',
          country: 'USA'
        },
        isVerified: true
      },
      {
        name: 'John Smith',
        email: 'john.farmer@example.com',
        password: 'password123',
        role: 'farmer',
        phone: '555-0103',
        farmerProfile: {
          farmName: 'Smith Family Farm',
          farmSize: 25,
          farmingMethods: ['Traditional', 'Sustainable'],
          description: 'Third-generation family farm growing seasonal vegetables.',
          location: {
            latitude: 34.1522,
            longitude: -118.1437
          }
        },
        isVerified: true
      }
    ];

    const createdUsers = await User.insertMany(demoUsers);
    console.log('Created demo users');

    // Find farmers for product creation
    const farmers = createdUsers.filter(user => user.role === 'farmer');

    // Create comprehensive demo products with natural photos
    const demoProducts = [
      // VEGETABLES
      {
        name: 'Fresh Organic Tomatoes',
        description: 'Vine-ripened organic tomatoes, perfect for salads and cooking. Grown without pesticides in rich soil.',
        category: 'vegetables',
        price: 120,
        unit: 'lb',
        quantity: 50,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1546470427-e5b89b618b84?w=500&h=500&fit=crop']
      },
      {
        name: 'Sweet Corn',
        description: 'Fresh sweet corn picked this morning. Perfect for grilling, boiling, or making corn salad.',
        category: 'vegetables',
        price: 15,
        unit: 'piece',
        quantity: 100,
        farmer: farmers[0]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Carrots',
        description: 'Sweet, crunchy organic carrots. Great for snacking, cooking, or juicing. Rich in beta-carotene.',
        category: 'vegetables',
        price: 80,
        unit: 'lb',
        quantity: 60,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1445282768818-728615cc910a?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Lettuce',
        description: 'Crisp romaine lettuce, perfect for salads and sandwiches. Grown in greenhouse conditions.',
        category: 'vegetables',
        price: 40,
        unit: 'piece',
        quantity: 40,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.0,
        images: ['https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500&h=500&fit=crop']
      },
      {
        name: 'Bell Peppers',
        description: 'Colorful bell peppers - red, yellow, and green. Sweet and crunchy, perfect for stir-fries.',
        category: 'vegetables',
        price: 95,
        unit: 'lb',
        quantity: 35,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Broccoli',
        description: 'Nutrient-rich broccoli crowns. Excellent source of vitamins C and K. Perfect for steaming.',
        category: 'vegetables',
        price: 110,
        unit: 'lb',
        quantity: 25,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.1,
        images: ['https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Spinach',
        description: 'Fresh baby spinach leaves. Perfect for salads, smoothies, or sautéing. Rich in iron.',
        category: 'vegetables',
        price: 85,
        unit: 'lb',
        quantity: 30,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&h=500&fit=crop']
      },
      {
        name: 'Red Onions',
        description: 'Sharp, flavorful red onions. Essential for cooking and adds great taste to any dish.',
        category: 'vegetables',
        price: 60,
        unit: 'lb',
        quantity: 80,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Cucumbers',
        description: 'Crisp, refreshing cucumbers. Great for salads, pickles, or eating fresh. Very hydrating.',
        category: 'vegetables',
        price: 70,
        unit: 'lb',
        quantity: 45,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=500&h=500&fit=crop']
      },
      {
        name: 'Baby Potatoes',
        description: 'Small, tender baby potatoes. Perfect for roasting, boiling, or making potato salad.',
        category: 'vegetables',
        price: 55,
        unit: 'lb',
        quantity: 70,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.0,
        images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&h=500&fit=crop']
      },

      // FRUITS
      {
        name: 'Organic Strawberries',
        description: 'Sweet, juicy organic strawberries. Great for desserts, smoothies, or eating fresh.',
        category: 'fruits',
        price: 180,
        unit: 'lb',
        quantity: 30,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.8,
        images: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Apples',
        description: 'Crisp, sweet apples. Perfect for snacking, baking, or making fresh apple juice.',
        category: 'fruits',
        price: 130,
        unit: 'lb',
        quantity: 60,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&h=500&fit=crop']
      },
      {
        name: 'Ripe Bananas',
        description: 'Sweet, ripe bananas. Great for smoothies, baking, or eating as a healthy snack.',
        category: 'fruits',
        price: 45,
        unit: 'lb',
        quantity: 50,
        farmer: farmers[0]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Oranges',
        description: 'Juicy, vitamin C-rich oranges. Perfect for fresh juice or eating as a healthy snack.',
        category: 'fruits',
        price: 90,
        unit: 'lb',
        quantity: 40,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1547514701-42782101795e?w=500&h=500&fit=crop']
      },
      {
        name: 'Blueberries',
        description: 'Antioxidant-rich blueberries. Perfect for smoothies, pancakes, or eating fresh.',
        category: 'fruits',
        price: 220,
        unit: 'lb',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Grapes',
        description: 'Sweet, seedless grapes. Great for snacking, making juice, or adding to fruit salads.',
        category: 'fruits',
        price: 160,
        unit: 'lb',
        quantity: 35,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=500&h=500&fit=crop']
      },
      {
        name: 'Ripe Avocados',
        description: 'Creamy, ripe avocados. Perfect for guacamole, toast, or adding to salads.',
        category: 'fruits',
        price: 200,
        unit: 'lb',
        quantity: 25,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Lemons',
        description: 'Tart, juicy lemons. Essential for cooking, baking, and making fresh lemonade.',
        category: 'fruits',
        price: 110,
        unit: 'lb',
        quantity: 30,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.1,
        images: ['https://images.unsplash.com/photo-1590502593747-42a4501a2395?w=500&h=500&fit=crop']
      },
      {
        name: 'Sweet Mangoes',
        description: 'Tropical, sweet mangoes. Perfect for smoothies, desserts, or eating fresh.',
        category: 'fruits',
        price: 150,
        unit: 'lb',
        quantity: 28,
        farmer: farmers[0]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Pineapple',
        description: 'Sweet, tropical pineapple. Rich in vitamin C and perfect for fresh eating or smoothies.',
        category: 'fruits',
        price: 80,
        unit: 'piece',
        quantity: 15,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=500&h=500&fit=crop']
      },

      // MORE VEGETABLES
      {
        name: 'Fresh Cabbage',
        description: 'Crisp green cabbage. Perfect for coleslaw, stir-fries, and soups. Rich in vitamin C.',
        category: 'vegetables',
        price: 50,
        unit: 'piece',
        quantity: 35,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.1,
        images: ['https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Cauliflower',
        description: 'White cauliflower heads. Versatile vegetable perfect for roasting, mashing, or making rice.',
        category: 'vegetables',
        price: 90,
        unit: 'piece',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1568584711271-946d4d46d0d5?w=500&h=500&fit=crop']
      },
      {
        name: 'Green Beans',
        description: 'Fresh green beans. Crisp and tender, perfect for steaming, sautéing, or adding to casseroles.',
        category: 'vegetables',
        price: 100,
        unit: 'lb',
        quantity: 40,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1553621042-f6e147245754?w=500&h=500&fit=crop']
      },
      {
        name: 'Sweet Potatoes',
        description: 'Orange sweet potatoes. Rich in beta-carotene and fiber. Great for baking or roasting.',
        category: 'vegetables',
        price: 75,
        unit: 'lb',
        quantity: 50,
        farmer: farmers[0]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Zucchini',
        description: 'Tender zucchini squash. Perfect for grilling, baking bread, or making noodles.',
        category: 'vegetables',
        price: 85,
        unit: 'lb',
        quantity: 30,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.0,
        images: ['https://images.unsplash.com/photo-1597362925123-77861d3fbac7?w=500&h=500&fit=crop']
      },

      // MORE FRUITS
      {
        name: 'Fresh Watermelon',
        description: 'Sweet, juicy watermelon. Perfect for hot summer days. Very hydrating and refreshing.',
        category: 'fruits',
        price: 60,
        unit: 'piece',
        quantity: 15,
        farmer: farmers[0]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Peaches',
        description: 'Juicy, sweet peaches. Perfect for eating fresh, making pies, or preserves.',
        category: 'fruits',
        price: 140,
        unit: 'lb',
        quantity: 25,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1629828874514-d71ba34d2b3a?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Cherries',
        description: 'Sweet red cherries. Perfect for snacking, baking, or making jams. Rich in antioxidants.',
        category: 'fruits',
        price: 250,
        unit: 'lb',
        quantity: 18,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.8,
        images: ['https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Pears',
        description: 'Sweet, juicy pears. Great for eating fresh, baking, or making preserves.',
        category: 'fruits',
        price: 120,
        unit: 'lb',
        quantity: 35,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Kiwi',
        description: 'Tangy kiwi fruits. Rich in vitamin C and fiber. Great for smoothies or eating fresh.',
        category: 'fruits',
        price: 180,
        unit: 'lb',
        quantity: 22,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1585059895524-72359e06133a?w=500&h=500&fit=crop']
      },

      // GRAINS
      {
        name: 'Organic Brown Rice',
        description: 'Whole grain brown rice. Nutty flavor and chewy texture. Rich in fiber and nutrients.',
        category: 'grains',
        price: 180,
        unit: 'lb',
        quantity: 100,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&h=500&fit=crop']
      },
      {
        name: 'Whole Wheat Flour',
        description: 'Stone-ground whole wheat flour. Perfect for baking bread, cookies, and pastries.',
        category: 'grains',
        price: 120,
        unit: 'lb',
        quantity: 80,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Quinoa',
        description: 'Protein-rich quinoa seeds. Gluten-free superfood perfect for salads and bowls.',
        category: 'grains',
        price: 320,
        unit: 'lb',
        quantity: 40,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Steel Cut Oats',
        description: 'Hearty steel-cut oats. Perfect for breakfast porridge. High in fiber and protein.',
        category: 'grains',
        price: 150,
        unit: 'lb',
        quantity: 60,
        farmer: farmers[1]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Barley',
        description: 'Whole grain barley. Great for soups, stews, and salads. Rich in fiber and minerals.',
        category: 'grains',
        price: 140,
        unit: 'lb',
        quantity: 50,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.1,
        images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Buckwheat',
        description: 'Gluten-free buckwheat groats. Nutty flavor, perfect for pancakes and porridge. High in protein.',
        category: 'grains',
        price: 200,
        unit: 'lb',
        quantity: 35,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Wild Rice',
        description: 'Premium wild rice. Nutty, chewy texture. Perfect for stuffing and grain bowls.',
        category: 'grains',
        price: 380,
        unit: 'lb',
        quantity: 25,
        farmer: farmers[0]._id,
        isOrganic: false,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Millet',
        description: 'Ancient grain millet. Gluten-free, high in magnesium. Great for porridge and baking.',
        category: 'grains',
        price: 160,
        unit: 'lb',
        quantity: 45,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Amaranth',
        description: 'Protein-rich amaranth seeds. Ancient superfood, gluten-free. Perfect for breakfast bowls.',
        category: 'grains',
        price: 280,
        unit: 'lb',
        quantity: 30,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Spelt Flour',
        description: 'Ancient grain spelt flour. Nutty flavor, easier to digest than wheat. Perfect for artisan baking.',
        category: 'grains',
        price: 180,
        unit: 'lb',
        quantity: 40,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Chia Seeds',
        description: 'Superfood chia seeds. Rich in omega-3, fiber, and protein. Perfect for smoothies and puddings.',
        category: 'grains',
        price: 350,
        unit: 'lb',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.8,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Flax Seeds',
        description: 'Golden flax seeds. High in omega-3 fatty acids and lignans. Great for baking and smoothies.',
        category: 'grains',
        price: 220,
        unit: 'lb',
        quantity: 35,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Hemp Seeds',
        description: 'Hulled hemp hearts. Complete protein source with perfect amino acid profile. Nutty flavor.',
        category: 'grains',
        price: 400,
        unit: 'lb',
        quantity: 15,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Sunflower Seeds',
        description: 'Raw sunflower seeds. Rich in vitamin E and healthy fats. Perfect for snacking and baking.',
        category: 'grains',
        price: 180,
        unit: 'lb',
        quantity: 45,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },
      {
        name: 'Organic Pumpkin Seeds',
        description: 'Raw pumpkin seeds (pepitas). High in magnesium and zinc. Great for snacking and salads.',
        category: 'grains',
        price: 280,
        unit: 'lb',
        quantity: 25,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&h=500&fit=crop']
      },

      // DAIRY PRODUCTS
      {
        name: 'Farm Fresh Eggs',
        description: 'Free-range chicken eggs from happy hens. Rich, flavorful, and nutritious.',
        category: 'dairy',
        price: 150,
        unit: 'dozen',
        quantity: 25,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Whole Milk',
        description: 'Creamy whole milk from grass-fed cows. Rich in calcium and vitamins.',
        category: 'dairy',
        price: 80,
        unit: 'liter',
        quantity: 30,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&h=500&fit=crop']
      },
      {
        name: 'Artisan Cheese',
        description: 'Handcrafted farmhouse cheese. Aged to perfection with rich, complex flavors.',
        category: 'dairy',
        price: 280,
        unit: 'lb',
        quantity: 15,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.8,
        images: ['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=500&h=500&fit=crop']
      },
      {
        name: 'Greek Yogurt',
        description: 'Thick, creamy Greek yogurt. High in protein and probiotics. Made from organic milk.',
        category: 'dairy',
        price: 120,
        unit: 'lb',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=500&fit=crop']
      },
      {
        name: 'Farm Butter',
        description: 'Creamy farm-fresh butter. Made from cream of grass-fed cows. Perfect for cooking and baking.',
        category: 'dairy',
        price: 200,
        unit: 'lb',
        quantity: 18,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&h=500&fit=crop']
      },

      // MEAT PRODUCTS
      {
        name: 'Grass-Fed Beef',
        description: 'Premium grass-fed beef. Lean, flavorful, and ethically raised. Perfect for grilling.',
        category: 'meat',
        price: 450,
        unit: 'lb',
        quantity: 25,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.8,
        images: ['https://images.unsplash.com/photo-1588347818133-38c4106ca7b4?w=500&h=500&fit=crop']
      },
      {
        name: 'Free-Range Chicken',
        description: 'Free-range chicken breast. Tender and flavorful. Raised without antibiotics.',
        category: 'meat',
        price: 320,
        unit: 'lb',
        quantity: 30,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&h=500&fit=crop']
      },
      {
        name: 'Heritage Pork',
        description: 'Heritage breed pork. Rich flavor and marbling. Raised on pasture with natural diet.',
        category: 'meat',
        price: 380,
        unit: 'lb',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1588347818133-38c4106ca7b4?w=500&h=500&fit=crop']
      },
      {
        name: 'Farm-Raised Turkey',
        description: 'Free-range turkey. Lean protein, perfect for healthy meals. Raised without hormones.',
        category: 'meat',
        price: 350,
        unit: 'lb',
        quantity: 15,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&h=500&fit=crop']
      },

      // HERBS & SPICES
      {
        name: 'Fresh Basil',
        description: 'Aromatic fresh basil leaves. Perfect for pasta, pizza, and Mediterranean dishes.',
        category: 'herbs',
        price: 25,
        unit: 'piece',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.7,
        images: ['https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Cilantro',
        description: 'Fresh cilantro leaves. Essential for Mexican, Indian, and Asian cuisines.',
        category: 'herbs',
        price: 20,
        unit: 'piece',
        quantity: 25,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1583119022894-e2e7b8b8c9b5?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Rosemary',
        description: 'Fragrant rosemary sprigs. Perfect for roasting meats and vegetables. Aromatic and flavorful.',
        category: 'herbs',
        price: 30,
        unit: 'piece',
        quantity: 18,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1515426954248-2df4c11837d8?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Thyme',
        description: 'Delicate thyme leaves. Essential herb for French cuisine. Great with poultry and vegetables.',
        category: 'herbs',
        price: 28,
        unit: 'piece',
        quantity: 22,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1515426954248-2df4c11837d8?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Oregano',
        description: 'Pungent oregano leaves. Essential for Italian and Greek cooking. Perfect for pizza and pasta.',
        category: 'herbs',
        price: 26,
        unit: 'piece',
        quantity: 20,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1515426954248-2df4c11837d8?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Parsley',
        description: 'Bright green parsley. Perfect garnish and ingredient. Rich in vitamins and minerals.',
        category: 'herbs',
        price: 22,
        unit: 'piece',
        quantity: 30,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.2,
        images: ['https://images.unsplash.com/photo-1583119022894-e2e7b8b8c9b5?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Mint',
        description: 'Refreshing mint leaves. Perfect for teas, cocktails, and Middle Eastern dishes. Very aromatic.',
        category: 'herbs',
        price: 24,
        unit: 'piece',
        quantity: 25,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.6,
        images: ['https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Sage',
        description: 'Earthy sage leaves. Perfect for roasted meats and autumn dishes. Strong, distinctive flavor.',
        category: 'herbs',
        price: 32,
        unit: 'piece',
        quantity: 18,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.4,
        images: ['https://images.unsplash.com/photo-1515426954248-2df4c11837d8?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Dill',
        description: 'Feathery dill fronds. Essential for Scandinavian and Eastern European cuisine. Great with fish.',
        category: 'herbs',
        price: 26,
        unit: 'piece',
        quantity: 22,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.3,
        images: ['https://images.unsplash.com/photo-1583119022894-e2e7b8b8c9b5?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Chives',
        description: 'Mild onion-flavored chives. Perfect for garnishing soups, salads, and egg dishes.',
        category: 'herbs',
        price: 20,
        unit: 'piece',
        quantity: 28,
        farmer: farmers[1]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.1,
        images: ['https://images.unsplash.com/photo-1583119022894-e2e7b8b8c9b5?w=500&h=500&fit=crop']
      },
      {
        name: 'Fresh Tarragon',
        description: 'Anise-flavored tarragon. Essential for French cuisine. Perfect with chicken and fish dishes.',
        category: 'herbs',
        price: 35,
        unit: 'piece',
        quantity: 15,
        farmer: farmers[0]._id,
        isOrganic: true,
        harvestDate: new Date(),
        expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        isAvailable: true,
        averageRating: 4.5,
        images: ['https://images.unsplash.com/photo-1515426954248-2df4c11837d8?w=500&h=500&fit=crop']
      }
    ];

    await Product.insertMany(demoProducts);
    console.log('Created demo products');

    console.log('Seed data created successfully!');
    console.log('\nDemo accounts:');
    console.log('Farmer: farmer@demo.com / demo123');
    console.log('Consumer: consumer@demo.com / demo123');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedData();